### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by StronglyHoldTV** [Flowsqy/ShopChest#27]
I am using Paper version 1.21-37-master@dd49fba. I get error message during startup.

`[13:49:23] [Server thread/INFO]: [ShopChest] Enabling ShopChest v1.14.0-SNAPSHOT
[13:49:24] [Server thread/ERROR]: Error occurred while enabling ShopChest v1.14.0-SNAPSHOT (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at ShopChest-1.14.0-SNAPSHOT.jar/de.epiceric.shopchest.utils.Utils.getMajorVersion(Utils.java:334) ~[ShopChest-1.14.0-SNAPSHOT.jar:?]
	at ShopChest-1.14.0-SNAPSHOT.jar/de.epiceric.shopchest.ShopChest.hasPlotSquared(ShopChest.java:624) ~[ShopChest-1.14.0-SNAPSHOT.jar:?]
	at ShopChest-1.14.0-SNAPSHOT.jar/de.epiceric.shopchest.ShopChest.loadExternalPlugins(ShopChest.java:309) ~[ShopChest-1.14.0-SNAPSHOT.jar:?]
	at ShopChest-1.14.0-SNAPSHOT.jar/de.epiceric.shopchest.ShopChest.onEnable(ShopChest.java:188) ~[ShopChest-1.14.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-37-dd49fba]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-37-dd49fba]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:49:24] [Server thread/INFO]: [ShopChest] Disabling ShopChest v1.14.0-SNAPSHOT`

**Comment by Flowsqy** [comment]
Yeah, apparently paper decided to do breaking changes for no reason. I will fix that later, but if just want to try the plugin in the upcoming two hours, you can use spigot.

**Comment by Flowsqy** [comment]
I updated the last release. You can download from there to get the fix. Thx for the issue.
